# Generated by Django 2.1.5 on 2019-04-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.BigIntegerField(db_index=True, unique=True)),
                ('count_users', models.IntegerField(default=0)),
            ],
        ),
    ]
