# Generated by Django 2.1.5 on 2019-04-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('user_nickname', models.CharField(max_length=30)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(default='пусто')),
            ],
        ),
    ]
