# Generated by Django 2.1.5 on 2019-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_message_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
