# Generated by Django 2.1.5 on 2019-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20190706_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
