# Generated by Django 2.1.5 on 2019-07-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_chat_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='alco_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='bones_on',
            field=models.BooleanField(default=True),
        ),
    ]
