# Generated by Django 2.1.5 on 2019-01-26 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('warrior', models.IntegerField(default=0)),
                ('warrior_hp', models.IntegerField(default=10)),
                ('warrior_attack', models.IntegerField(default=5)),
                ('archer', models.IntegerField(default=0)),
                ('archer_hp', models.IntegerField(default=10)),
                ('archer_attack', models.IntegerField(default=15)),
                ('wizard', models.IntegerField(default=0)),
                ('wizard_hp', models.IntegerField(default=10)),
                ('wizard_attack', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('forge', models.BooleanField(default=False)),
                ('tavern', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('need', models.IntegerField(default=30)),
                ('sword', models.IntegerField(default=0)),
                ('bow', models.IntegerField(default=0)),
                ('orb', models.IntegerField(default=0)),
                ('pickaxe_stone', models.BooleanField(default=False)),
                ('pickaxe_iron', models.BooleanField(default=False)),
                ('pickaxe_diamond', models.BooleanField(default=False)),
                ('pickaxe_skull', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('lvl', models.IntegerField(default=1)),
                ('exp_need', models.BigIntegerField(default=10)),
                ('exp', models.BigIntegerField(default=0)),
                ('energy', models.IntegerField(default=10)),
                ('max_energy', models.IntegerField(default=10)),
                ('last_energy_action', models.BigIntegerField(default=0)),
                ('energy_regen', models.IntegerField(default=1)),
                ('place', models.CharField(default='cave', max_length=50)),
                ('army', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digger.Army')),
                ('build', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digger.Build')),
                ('forge', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digger.Forge')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('lvl', models.IntegerField(default=1)),
                ('need', models.IntegerField(default=50)),
                ('wood', models.IntegerField(default=0)),
                ('wood_max', models.IntegerField(default=100)),
                ('stone', models.IntegerField(default=0)),
                ('stone_max', models.IntegerField(default=100)),
                ('diamond', models.IntegerField(default=0)),
                ('diamond_max', models.IntegerField(default=100)),
                ('iron', models.IntegerField(default=0)),
                ('iron_max', models.IntegerField(default=100)),
                ('gold', models.IntegerField(default=0)),
                ('gold_max', models.IntegerField(default=100)),
                ('skull', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tavern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('need_stone', models.IntegerField(default=30)),
                ('need_iron', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digger.Stock'),
        ),
        migrations.AddField(
            model_name='player',
            name='tavern',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='digger.Tavern'),
        ),
    ]
