# Generated by Django 2.1.5 on 2019-01-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='lift',
            new_name='gate',
        ),
    ]
