# Generated by Django 2.1.5 on 2019-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0002_auto_20190129_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='tower_lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='build',
            name='tower_need_stone',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='build',
            name='tower_need_wood',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='build',
            name='wall_lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='build',
            name='wall_need_stone',
            field=models.IntegerField(default=100),
        ),
    ]
