# Generated by Django 2.1.5 on 2019-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0003_auto_20190129_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tavern',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='diamond_max',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='gold_max',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='iron_max',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stone_max',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='wood_max',
        ),
        migrations.AddField(
            model_name='stock',
            name='max',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='build',
            name='wall_need_stone',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='exp_need',
            field=models.BigIntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='Tavern',
        ),
    ]
