# Generated by Django 2.1.5 on 2019-02-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0006_auto_20190207_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='war',
            name='shield_type',
        ),
        migrations.AddField(
            model_name='war',
            name='shield',
            field=models.IntegerField(default=0),
        ),
    ]
