# Generated by Django 2.1.5 on 2019-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0008_auto_20190207_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
