# Generated by Django 2.1.5 on 2019-02-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0009_player_bonus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='archer_attack',
        ),
        migrations.RemoveField(
            model_name='army',
            name='archer_hp',
        ),
        migrations.RemoveField(
            model_name='army',
            name='warrior_attack',
        ),
        migrations.RemoveField(
            model_name='army',
            name='warrior_hp',
        ),
        migrations.RemoveField(
            model_name='army',
            name='wizard_attack',
        ),
        migrations.RemoveField(
            model_name='army',
            name='wizard_hp',
        ),
    ]
