# Generated by Django 2.1.5 on 2019-02-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0010_auto_20190208_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defend',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='win',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='defend_last_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
