# Generated by Django 2.1.5 on 2019-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0011_auto_20190209_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='gate',
            new_name='citadel',
        ),
        migrations.RemoveField(
            model_name='build',
            name='tower_need',
        ),
        migrations.RemoveField(
            model_name='build',
            name='wall_need',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='need',
        ),
        migrations.AlterField(
            model_name='build',
            name='tower_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='build',
            name='wall_lvl',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_energy',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='max',
            field=models.IntegerField(default=60),
        ),
    ]
