# Generated by Django 2.1.5 on 2019-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digger', '0012_auto_20190215_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crusade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('part', models.IntegerField(default=0)),
                ('crusade_last_time', models.BigIntegerField(default=0)),
                ('enemy', models.CharField(blank=True, default='', max_length=30)),
                ('enemy_army', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='player',
            name='crusade',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), to='digger.Crusade'),
        ),
    ]
