# Generated by Django 2.1.5 on 2019-03-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('forge', models.BooleanField(default=False)),
                ('tavern', models.BooleanField(default=False)),
                ('citadel', models.IntegerField(default=0)),
                ('tower_lvl', models.IntegerField(default=0)),
                ('wall_lvl', models.IntegerField(default=0)),
                ('stone_pit_lvl', models.IntegerField(default=0)),
                ('mine_lvl', models.IntegerField(default=0)),
                ('sawmill_lvl', models.IntegerField(default=0)),
                ('minning_camp_lvl', models.IntegerField(default=0)),
                ('altar', models.BooleanField(default=False)),
                ('exchange', models.BooleanField(default=False)),
                ('barracks', models.BooleanField(default=False)),
                ('archery', models.BooleanField(default=False)),
                ('magic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('nickname', models.CharField(blank=True, default='', max_length=30)),
                ('lvl', models.IntegerField(default=1)),
                ('exp_need', models.BigIntegerField(default=3)),
                ('exp', models.BigIntegerField(default=0)),
                ('energy', models.IntegerField(default=30)),
                ('max_energy', models.IntegerField(default=30)),
                ('last_energy_action', models.BigIntegerField(default=0)),
                ('energy_regen', models.IntegerField(default=1)),
                ('bonus_time', models.BigIntegerField(default=0)),
                ('place', models.CharField(default='cave', max_length=50)),
                ('build', models.OneToOneField(null=True, on_delete=models.SET(None), to='game.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('lvl', models.IntegerField(default=1)),
                ('max', models.IntegerField(default=60)),
                ('wood', models.IntegerField(default=0)),
                ('stone', models.IntegerField(default=0)),
                ('diamond', models.IntegerField(default=0)),
                ('iron', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('skull', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('enemy_id', models.BigIntegerField(blank=True, null=True)),
                ('shield', models.IntegerField(default=0)),
                ('find_last_time', models.BigIntegerField(default=0)),
                ('war_last_time', models.BigIntegerField(default=0)),
                ('defend_last_time', models.BigIntegerField(default=0)),
                ('boss_last_time', models.BigIntegerField(default=0)),
                ('crusade_last_time', models.BigIntegerField(default=0)),
                ('crusade_part', models.IntegerField(default=0)),
                ('enemy', models.CharField(blank=True, default='', max_length=30)),
                ('enemy_armyenemy_army', models.IntegerField(default=0)),
                ('warrior', models.IntegerField(default=0)),
                ('archer', models.IntegerField(default=0)),
                ('wizard', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='war',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), to='game.War'),
        ),
        migrations.AddField(
            model_name='build',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), to='game.Stock'),
        ),
    ]
