# Generated by Django 2.1.5 on 2019-04-12 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chestitem',
            options={'verbose_name': 'Сундук с предметом', 'verbose_name_plural': 'Сундуки с предметами'},
        ),
        migrations.AlterModelOptions(
            name='chesttrophy',
            options={'verbose_name': 'Сундук с трофеем', 'verbose_name_plural': 'Сундуки с трофеями'},
        ),
        migrations.AlterModelOptions(
            name='inventorychest',
            options={'verbose_name': 'Инвентарь сундуков', 'verbose_name_plural': 'Инвентари сундуков'},
        ),
        migrations.AlterModelOptions(
            name='inventorytrophy',
            options={'verbose_name': 'Инвентарь трофеев', 'verbose_name_plural': 'Инвентари трофеев'},
        ),
    ]
