# Generated by Django 2.1.5 on 2019-03-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190314_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='mine_lvl',
            new_name='diamond_mine_lvl',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='minning_camp_lvl',
            new_name='iron_mine_lvl',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='sawmill_lvl',
            new_name='stone_mine_lvl',
        ),
        migrations.RenameField(
            model_name='build',
            old_name='stone_pit_lvl',
            new_name='wood_mine_lvl',
        ),
    ]
