# Generated by Django 2.1.5 on 2019-04-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190412_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
