# Generated by Django 2.1.5 on 2019-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='chance_for_get',
            field=models.FloatField(default=0),
        ),
    ]
