# Generated by Django 2.1.5 on 2019-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190314_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='exp_need',
        ),
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_energy',
            field=models.IntegerField(default=20),
        ),
    ]
