# Generated by Django 2.1.5 on 2019-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_chest_chance_for_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='power',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
