# Generated by Django 2.1.5 on 2019-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_war_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='war',
            name='power',
        ),
        migrations.AlterField(
            model_name='build',
            name='stock',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='build', to='game.Stock'),
        ),
        migrations.AlterField(
            model_name='player',
            name='build',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='player', to='game.Build'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='player', to='game.Inventory'),
        ),
        migrations.AlterField(
            model_name='player',
            name='war',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='player', to='game.War'),
        ),
    ]
