# Generated by Django 2.1.5 on 2019-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20190314_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='war',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), to='game.War'),
        ),
    ]
