# Generated by Django 2.1.5 on 2019-04-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20190428_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='energy',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='max_energy',
            field=models.IntegerField(default=30),
        ),
    ]
