# Generated by Django 2.1.5 on 2019-03-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_war'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ChestChance',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('chance', models.FloatField(default=0)),
                ('chest', models.ManyToManyField(to='game.Chest')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('effects', models.ManyToManyField(to='game.Effect')),
            ],
        ),
        migrations.CreateModel(
            name='ItemChance',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('chance', models.FloatField(default=0)),
                ('item', models.ManyToManyField(to='game.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrophyChance',
            fields=[
                ('id', models.BigIntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('chance', models.FloatField(default=0)),
                ('trophy', models.ManyToManyField(to='game.Trophy')),
            ],
        ),
        migrations.AddField(
            model_name='chest',
            name='items_chance',
            field=models.ManyToManyField(to='game.ItemChance'),
        ),
        migrations.AddField(
            model_name='chest',
            name='trophy_chance',
            field=models.ManyToManyField(to='game.TrophyChance'),
        ),
    ]
