# Generated by Django 2.1.5 on 2019-03-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190315_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chestchance',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itemchance',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trophychance',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
