# Generated by Django 2.1.5 on 2019-04-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190428_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='war',
            name='success_attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='war',
            name='success_defend',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='war',
            name='shield',
            field=models.BigIntegerField(default=0),
        ),
    ]
