# Generated by Django 2.1.5 on 2019-05-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190429_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wood', 'Дерево'), ('stone', 'Камень'), ('iron', 'Железо'), ('diamond', 'Кристаллы')], max_length=30)),
                ('seller', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('unit_price', models.FloatField(blank=True)),
            ],
        ),
    ]
