# Generated by Django 2.1.5 on 2019-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190315_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='items_chance',
            field=models.ManyToManyField(blank=True, to='game.ItemChance'),
        ),
        migrations.AlterField(
            model_name='chest',
            name='trophy_chance',
            field=models.ManyToManyField(blank=True, to='game.TrophyChance'),
        ),
    ]
