# Generated by Django 2.1.5 on 2019-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20190315_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
