# Generated by Django 2.1.5 on 2019-05-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20190502_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lots',
            field=models.IntegerField(default=0),
        ),
    ]
