# Generated by Django 2.1.5 on 2019-05-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_player_lots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='build',
            old_name='exchange',
            new_name='market',
        ),
        migrations.RemoveField(
            model_name='player',
            name='lots',
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='products', to='game.Player'),
        ),
    ]
