# Generated by Django 2.1.5 on 2019-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190315_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
        migrations.AlterModelOptions(
            name='chest',
            options={'verbose_name': 'Сундук', 'verbose_name_plural': 'Сундуки'},
        ),
        migrations.AlterModelOptions(
            name='chestchance',
            options={'verbose_name': 'Шанс сундука', 'verbose_name_plural': 'Шансы сундуков'},
        ),
        migrations.AlterModelOptions(
            name='effect',
            options={'verbose_name': 'Эффект', 'verbose_name_plural': 'Эффекты'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентарь', 'verbose_name_plural': 'Инвентари'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='itemchance',
            options={'verbose_name': 'Шанс предмета', 'verbose_name_plural': 'Шансы предметов'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': 'Трофей(дроп)', 'verbose_name_plural': 'Трофеи(дроп)'},
        ),
        migrations.AlterModelOptions(
            name='trophychance',
            options={'verbose_name': 'Шанс трофея', 'verbose_name_plural': 'Шансы трофеев'},
        ),
        migrations.AlterModelOptions(
            name='war',
            options={'verbose_name': 'Война', 'verbose_name_plural': 'Войны'},
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), to='game.Inventory'),
        ),
    ]
