# Generated by Django 2.1.5 on 2019-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20190502_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='market',
        ),
        migrations.AddField(
            model_name='build',
            name='market_lvl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='build',
            name='market_send_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
