# Generated by Django 2.1.5 on 2019-03-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20190316_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chest',
            old_name='type',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='trophy',
            name='type',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='trophy',
            name='slug',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
