# Generated by Django 2.1.5 on 2019-05-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_auto_20190503_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='change_nickname_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
