# Generated by Django 2.1.5 on 2019-03-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20190316_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='nickname',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
    ]
