# Generated by Django 2.1.5 on 2019-05-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_player_change_nickname_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaveMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cave_map', models.TextField()),
                ('progress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaveProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('level', models.IntegerField()),
                ('cave', models.ForeignKey(null=True, on_delete=models.SET(None), to='game.CaveMap')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='cave_progress',
            field=models.OneToOneField(null=True, on_delete=models.SET(None), related_name='player', to='game.CaveProgress'),
        ),
    ]
