# Generated by Django 2.1.5 on 2019-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20190515_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavemap',
            name='progress',
        ),
        migrations.AddField(
            model_name='cavemap',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caveprogress',
            name='max_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='caveprogress',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
