# Generated by Django 2.1.5 on 2019-03-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20190318_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Chest')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='chests',
            field=models.ManyToManyField(blank=True, to='game.InventoryChest'),
        ),
    ]
