# Generated by Django 2.1.5 on 2019-03-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20190320_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorychest',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.Inventory'),
        ),
        migrations.AlterField(
            model_name='inventorychest',
            name='chest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Chest'),
        ),
    ]
