# Generated by Django 2.1.5 on 2019-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20190518_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('code', models.CharField(db_index=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cavemap',
            name='cave_map',
            field=models.TextField(blank=True),
        ),
    ]
