# Generated by Django 2.1.5 on 2019-03-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20190320_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorychest',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='inventorychest',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='chests',
        ),
        migrations.DeleteModel(
            name='InventoryChest',
        ),
    ]
