# Generated by Django 2.1.5 on 2019-05-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20190518_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavemap',
            name='success',
        ),
        migrations.AddField(
            model_name='caveprogress',
            name='success',
            field=models.IntegerField(default=0),
        ),
    ]
