# Generated by Django 2.1.5 on 2019-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20190519_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveprogress',
            name='cave_num',
            field=models.IntegerField(default=0),
        ),
    ]
