# Generated by Django 2.1.5 on 2019-03-20 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20190320_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Chest')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='game.Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='chests',
            field=models.ManyToManyField(blank=True, through='game.InventoryChest', to='game.Chest'),
        ),
    ]
