# Generated by Django 2.1.5 on 2019-03-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20190320_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='inventorychest',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Inventory'),
        ),
        migrations.AddField(
            model_name='inventorytrophy',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Inventory'),
        ),
        migrations.AddField(
            model_name='inventorytrophy',
            name='trophy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Trophy'),
        ),
    ]
