# Generated by Django 2.1.5 on 2019-03-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_auto_20190320_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorytrophy',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='inventorytrophy',
            name='trophy',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='trophy',
        ),
        migrations.DeleteModel(
            name='InventoryTrophy',
        ),
    ]
