# Generated by Django 2.1.5 on 2019-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_caveprogress_cave_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cave_progress',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(None), related_name='player', to='game.CaveProgress'),
        ),
    ]
