# Generated by Django 2.1.5 on 2019-05-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20190519_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveprogress',
            name='time',
            field=models.BigIntegerField(default=0),
        ),
    ]
