# Generated by Django 2.1.5 on 2019-03-20 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20190320_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Inventory')),
                ('trophy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Trophy')),
            ],
        ),
        migrations.RemoveField(
            model_name='chestchance',
            name='chest',
        ),
        migrations.RemoveField(
            model_name='itemchance',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trophychance',
            name='trophy',
        ),
        migrations.RemoveField(
            model_name='chest',
            name='items_chance',
        ),
        migrations.RemoveField(
            model_name='chest',
            name='trophy_chance',
        ),
        migrations.DeleteModel(
            name='ChestChance',
        ),
        migrations.DeleteModel(
            name='ItemChance',
        ),
        migrations.DeleteModel(
            name='TrophyChance',
        ),
        migrations.AddField(
            model_name='inventory',
            name='trophy',
            field=models.ManyToManyField(blank=True, through='game.InventoryTrophy', to='game.Trophy'),
        ),
    ]
