# Generated by Django 2.1.5 on 2019-05-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_caveprogress_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caveprogress',
            name='success',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
