# Generated by Django 2.1.5 on 2019-03-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20190320_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=0)),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Chest')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ChestTrophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField(default=0)),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Chest')),
                ('trophy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Trophy')),
            ],
        ),
        migrations.AddField(
            model_name='chest',
            name='items_chance',
            field=models.ManyToManyField(blank=True, through='game.ChestItem', to='game.Item'),
        ),
        migrations.AddField(
            model_name='chest',
            name='trophy_chance',
            field=models.ManyToManyField(blank=True, through='game.ChestTrophy', to='game.Trophy'),
        ),
    ]
