# Generated by Django 2.1.5 on 2019-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20190523_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='distribution',
            field=models.BooleanField(default=True),
        ),
    ]
