# Generated by Django 2.1.5 on 2019-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20190320_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='get_passive_last_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
