# Generated by Django 2.1.5 on 2019-06-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_player_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('wood', 'Дерево'), ('stone', 'Камень'), ('iron', 'Железо'), ('diamond', 'Кристаллы'), ('skull', 'Черепа')], max_length=30),
        ),
    ]
