# Generated by Django 2.1.5 on 2019-07-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190615_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alcohol_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
