# Generated by Django 2.1.5 on 2019-07-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_player_hunt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fortuna_coin',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='fortuna_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
