# Generated by Django 2.1.5 on 2019-07-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20190720_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='fortuna_coin',
            new_name='fortune_coin',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='fortuna_time',
            new_name='fortune_time',
        ),
    ]
