# Generated by Django 2.1.5 on 2019-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20190720_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caveprogress',
            name='max_level',
        ),
        migrations.AddField(
            model_name='caveprogress',
            name='player_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caveprogress',
            name='x',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='caveprogress',
            name='y',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
