# Generated by Django 2.1.5 on 2019-08-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_auto_20190803_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caveprogress',
            name='cave',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='game.CaveMap'),
        ),
    ]
